onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /MIPS_tb_basic/uut/AddressData_D
add wave -noupdate /MIPS_tb_basic/uut/AddressData_M
add wave -noupdate /MIPS_tb_basic/uut/AddressData_W
add wave -noupdate /MIPS_tb_basic/uut/AddressData_X
add wave -noupdate /MIPS_tb_basic/uut/alu_control_D
add wave -noupdate /MIPS_tb_basic/uut/alu_control_M
add wave -noupdate /MIPS_tb_basic/uut/alu_control_W
add wave -noupdate /MIPS_tb_basic/uut/alu_control_X
add wave -noupdate /MIPS_tb_basic/uut/ALUSrc_D
add wave -noupdate /MIPS_tb_basic/uut/ALUSrc_M
add wave -noupdate /MIPS_tb_basic/uut/ALUSrc_W
add wave -noupdate /MIPS_tb_basic/uut/ALUSrc_X
add wave -noupdate /MIPS_tb_basic/uut/BeqValid_M
add wave -noupdate /MIPS_tb_basic/uut/BeqValid_W
add wave -noupdate /MIPS_tb_basic/uut/BeqValid_X
add wave -noupdate /MIPS_tb_basic/uut/Branch_D
add wave -noupdate /MIPS_tb_basic/uut/Branch_M
add wave -noupdate /MIPS_tb_basic/uut/Branch_W
add wave -noupdate /MIPS_tb_basic/uut/Branch_X
add wave -noupdate /MIPS_tb_basic/uut/clk
add wave -noupdate /MIPS_tb_basic/uut/CurrentAddress_D
add wave -noupdate /MIPS_tb_basic/uut/CurrentAddress_F
add wave -noupdate /MIPS_tb_basic/uut/CurrentAddress_M
add wave -noupdate /MIPS_tb_basic/uut/CurrentAddress_W
add wave -noupdate /MIPS_tb_basic/uut/CurrentAddress_X
add wave -noupdate /MIPS_tb_basic/uut/CurrPc_Branch_F
add wave -noupdate /MIPS_tb_basic/uut/CurrPc_Jump_M
add wave -noupdate /MIPS_tb_basic/uut/CurrPc_Jump_W
add wave -noupdate /MIPS_tb_basic/uut/CurrPc_Jump_X
add wave -noupdate /MIPS_tb_basic/uut/Instruction_D
add wave -noupdate /MIPS_tb_basic/uut/Instruction_F
add wave -noupdate /MIPS_tb_basic/uut/Instruction_M
add wave -noupdate /MIPS_tb_basic/uut/Instruction_W
add wave -noupdate /MIPS_tb_basic/uut/Instruction_X
add wave -noupdate /MIPS_tb_basic/uut/Jump_D
add wave -noupdate /MIPS_tb_basic/uut/Jump_M
add wave -noupdate /MIPS_tb_basic/uut/Jump_W
add wave -noupdate /MIPS_tb_basic/uut/Jump_X
add wave -noupdate /MIPS_tb_basic/uut/MemRead_D
add wave -noupdate /MIPS_tb_basic/uut/MemRead_M
add wave -noupdate /MIPS_tb_basic/uut/MemRead_W
add wave -noupdate /MIPS_tb_basic/uut/MemRead_X
add wave -noupdate /MIPS_tb_basic/uut/MemToReg_D
add wave -noupdate /MIPS_tb_basic/uut/MemToReg_M
add wave -noupdate /MIPS_tb_basic/uut/MemToReg_W
add wave -noupdate /MIPS_tb_basic/uut/MemToReg_X
add wave -noupdate /MIPS_tb_basic/uut/MemWrite_D
add wave -noupdate /MIPS_tb_basic/uut/MemWrite_M
add wave -noupdate /MIPS_tb_basic/uut/MemWrite_W
add wave -noupdate /MIPS_tb_basic/uut/MemWrite_X
add wave -noupdate /MIPS_tb_basic/uut/muxALUSrc_D
add wave -noupdate /MIPS_tb_basic/uut/muxALUSrc_M
add wave -noupdate /MIPS_tb_basic/uut/muxALUSrc_W
add wave -noupdate /MIPS_tb_basic/uut/muxALUSrc_X
add wave -noupdate /MIPS_tb_basic/uut/muxMemToReg_W
add wave -noupdate /MIPS_tb_basic/uut/muxWriteReg_M
add wave -noupdate /MIPS_tb_basic/uut/muxWriteReg_W
add wave -noupdate /MIPS_tb_basic/uut/muxWriteReg_X
add wave -noupdate /MIPS_tb_basic/uut/pcOut_Branch_M
add wave -noupdate /MIPS_tb_basic/uut/pcOut_Branch_W
add wave -noupdate /MIPS_tb_basic/uut/pcOut_Branch_X
add wave -noupdate /MIPS_tb_basic/uut/pcOut_D
add wave -noupdate /MIPS_tb_basic/uut/pcOut_F
add wave -noupdate /MIPS_tb_basic/uut/pcOut_M
add wave -noupdate /MIPS_tb_basic/uut/pcOut_plus4_D
add wave -noupdate /MIPS_tb_basic/uut/pcOut_plus4_F
add wave -noupdate /MIPS_tb_basic/uut/pcOut_plus4_M
add wave -noupdate /MIPS_tb_basic/uut/pcOut_plus4_W
add wave -noupdate /MIPS_tb_basic/uut/pcOut_plus4_X
add wave -noupdate /MIPS_tb_basic/uut/pcOut_W
add wave -noupdate /MIPS_tb_basic/uut/pcOut_X
add wave -noupdate /MIPS_tb_basic/uut/ReadData1_D
add wave -noupdate /MIPS_tb_basic/uut/ReadData1_M
add wave -noupdate /MIPS_tb_basic/uut/ReadData1_W
add wave -noupdate /MIPS_tb_basic/uut/ReadData1_X
add wave -noupdate /MIPS_tb_basic/uut/ReadData2_D
add wave -noupdate /MIPS_tb_basic/uut/ReadData2_M
add wave -noupdate /MIPS_tb_basic/uut/ReadData2_W
add wave -noupdate /MIPS_tb_basic/uut/ReadData2_X
add wave -noupdate /MIPS_tb_basic/uut/ReadDataMem_M
add wave -noupdate /MIPS_tb_basic/uut/ReadDataMem_W
add wave -noupdate /MIPS_tb_basic/uut/RegDst_D
add wave -noupdate /MIPS_tb_basic/uut/RegDst_M
add wave -noupdate /MIPS_tb_basic/uut/RegDst_W
add wave -noupdate /MIPS_tb_basic/uut/muxMemToReg_W
add wave -noupdate /MIPS_tb_basic/uut/RegDst_X
add wave -noupdate /MIPS_tb_basic/uut/RegWrite_D
add wave -noupdate /MIPS_tb_basic/uut/RegWrite_M
add wave -noupdate /MIPS_tb_basic/uut/RegWrite_W
add wave -noupdate /MIPS_tb_basic/uut/RegWrite_X
add wave -noupdate /MIPS_tb_basic/uut/rst
add wave -noupdate /MIPS_tb_basic/uut/signExt_D
add wave -noupdate /MIPS_tb_basic/uut/signExt_M
add wave -noupdate /MIPS_tb_basic/uut/signExt_shift_M
add wave -noupdate /MIPS_tb_basic/uut/signExt_shift_W
add wave -noupdate /MIPS_tb_basic/uut/signExt_shift_X
add wave -noupdate /MIPS_tb_basic/uut/signExt_W
add wave -noupdate /MIPS_tb_basic/uut/signExt_X
add wave -noupdate /MIPS_tb_basic/uut/zero_M
add wave -noupdate /MIPS_tb_basic/uut/zero_W
add wave -noupdate /MIPS_tb_basic/uut/zero_X
add wave -noupdate -divider ALU
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_ctrl
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_result
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_signed
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_slt
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_src_a
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_src_b
add wave -noupdate /MIPS_tb_basic/uut/ALU/alu_zero
add wave -noupdate -divider REGBANK
add wave -noupdate /MIPS_tb_basic/uut/RegBank/clk
add wave -noupdate /MIPS_tb_basic/uut/RegBank/done
add wave -noupdate /MIPS_tb_basic/uut/RegBank/ReadData1
add wave -noupdate /MIPS_tb_basic/uut/RegBank/ReadData2
add wave -noupdate /MIPS_tb_basic/uut/RegBank/ReadReg1
add wave -noupdate /MIPS_tb_basic/uut/RegBank/ReadReg2
add wave -noupdate /MIPS_tb_basic/uut/RegBank/REG_FILE_DEPTH
add wave -noupdate /MIPS_tb_basic/uut/RegBank/RegBank
add wave -noupdate /MIPS_tb_basic/uut/RegBank/RegWrite
add wave -noupdate /MIPS_tb_basic/uut/RegBank/rst
add wave -noupdate /MIPS_tb_basic/uut/RegBank/WriteData
add wave -noupdate /MIPS_tb_basic/uut/RegBank/WriteReg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
